# Travis CI instructions

sudo: required
dist: trusty
language: generic

notifications:
  email:
    on_failure: always
    recipients:
      - a.gutenkunst@pilz.de
      - c.henkel@pilz.de
      - h.slusarek@pilz.de
      - i.martini@pilz.de
env:
  matrix:
    - ROS_DISTRO="melodic" ROS_REPO=ros-shadow-fixed CATKIN_LINT=true COVERAGE_PKGS="prbt_hardware_support pilz_control"
install:
  - git clone -b feature/coveralls --depth=1 https://github.com/ct2034/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
